In [43]:
import open3d as o3d
import numpy as np
import copy
import matplotlib.pyplot as plt

In [44]:
mesh_path = './models/Aric Board 2.stl'

mesh = o3d.io.read_triangle_mesh(mesh_path)

In [45]:
# Visualizing the mesh.
draw_geoms_list = [mesh]
o3d.visualization.draw_geometries(draw_geoms_list)

In [46]:
print(mesh)

TriangleMesh with 2048425 points and 683718 triangles.


In [47]:
# Computing the normals for the mesh.
mesh.compute_vertex_normals()

# Visualizing the mesh.
draw_geoms_list = [mesh]
o3d.visualization.draw_geometries(draw_geoms_list)

In [48]:
# Creating a mesh of the XYZ axes Cartesian coordinates frame.
# This mesh will show the directions in which the X, Y & Z-axes point,
# and can be overlaid on the 3D mesh to visualize its orientation in
# the Euclidean space.
# X-axis : Red arrow
# Y-axis : Green arrow
# Z-axis : Blue arrow
mesh_coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=30, origin=[0, 0, 0])

# Visualizing the mesh with the coordinate frame to understand the orientation.
draw_geoms_list = [mesh_coord_frame, mesh]
o3d.visualization.draw_geometries(draw_geoms_list)

In [49]:
# Creating a mesh of the XYZ axes Cartesian coordinates frame.
# This mesh will show the directions in which the X, Y & Z-axes point,
# and can be overlaid on the 3D mesh to visualize its orientation in
# the Euclidean space.
# X-axis : Red arrow
# Y-axis : Green arrow
# Z-axis : Blue arrow
mesh_coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=30, origin=[-300, 200, 200])

# Visualizing the mesh with the coordinate frame to understand the orientation.
draw_geoms_list = [mesh_coord_frame, mesh]
o3d.visualization.draw_geometries(draw_geoms_list)

In [76]:
mesh_path = './models/Aric Board 2.stl'
mesh = o3d.io.read_triangle_mesh(mesh_path)
mesh.compute_vertex_normals()


box = mesh.get_minimal_oriented_bounding_box(robust=True)
box.color = (1,0,0)

mesh_coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=30)
cone_height = 10
cylinder_height = (box.center**2).sum()**0.5 - cone_height
cylinder_height1 = (box.extent**2).sum()**0.5 - cone_height

arrow_center = mesh.create_arrow(cone_height=cone_height, cylinder_height=cylinder_height)
#first angle: arctan (y/x)
#second angle: arctan (y/M)
rotation = box.rotate

angle1 = 
#roatation represents how to draw the box
R = mesh.get_rotation_matrix_from_xyz((0, 2*np.pi/3 , 0))
arrow_center.rotate(R, center=(0,0,0))

arrow_extent = mesh.create_arrow(cone_height=cone_height, cylinder_height=cylinder_height1)

R1 = mesh.get_rotation_matrix_from_xyz((0, 2*np.pi/3 , 0))
arrow_extent.rotate(R1, center=(0,0,0))

o3d.visualization.draw_geometries([mesh, box, mesh_coord_frame, arrow_center, arrow_extent])

In [51]:
print(box)
print(box.extent)

#translate bounding box by extent. if this is center then this is valid.

OrientedBoundingBox: center: (-321.822, 175.297, 184.745), extent: 487.667, 90.3128, 42.2801)
[487.66676551  90.31280196  42.28007382]


In [69]:
rotated = box.rotate((-1)*box.R, box.center)
o3d.visualization.draw_geometries([rotated, mesh_coord_frame, mesh])

In [52]:
print(mesh.get_center())

[-320.66492028  183.06555677  175.37032867]


In [53]:
new_box = o3d.geometry.TriangleMesh.create_box(box.extent[0], box.extent[1], box.extent[2])

o3d.visualization.draw_geometries([new_box, mesh])

In [56]:
mesh_path = './models/Aric Board 2.stl'

mesh = o3d.io.read_triangle_mesh(mesh_path)
mesh.compute_vertex_normals()

box = mesh.get_minimal_oriented_bounding_box(robust=True)

extent = box.extent

old_center = mesh.get_center()

mesh1 = mesh.translate((-1)*old_center)
mesh2 = mesh.translate((1)*old_center)

new_mesh = mesh.translate((-1)*extent)

print(mesh.get_center())
o3d.visualization.draw_geometries([mesh,mesh1,mesh2, mesh_coord_frame])


[-808.33168575   92.75275481  133.09025484]


In [20]:
box = mesh.get_minimal_oriented_bounding_box(robust=True)
rect_mesh = o3d.geometry.TriangleMesh.create_box(box.extent[0], box.extent[1], box.extent[2])
mesh_coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=30, origin=[-1, 0, 0])
box_mesh_coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=30, origin=[0, 0, 0])
o3d.visualization.draw_geometries([box, mesh, mesh_coord_frame, box_mesh_coord_frame])

# mesh of rect_mesh is positioned so that bottom right corner is (0,0,0). while original mesh is not. need to find a way to position original mesh into the position!!

box = mesh.get_minimal_oriented_bounding_box(robust=True)

In [15]:
print(mesh)
box = mesh.get_minimal_oriented_bounding_box(robust=True)
print(box)

TriangleMesh with 2048425 points and 683718 triangles.
OrientedBoundingBox: center: (-1.15677, -7.76896, 9.37472), extent: 487.667, 90.3128, 42.2801)


In [18]:
box.get_rotation_matrix_from_xyz((2,2,2))

array([[ 0.17317819,  0.37840125,  0.90929743],
       [-0.72248053, -0.57864876,  0.37840125],
       [ 0.66935133, -0.72248053,  0.17317819]])

ASSUMPTION: model is calibrated so that axis fits perfectly in bottom right hand corner - I am going to manually translate+rotate mesh until fits as such. This is because when using the create_box function, the mesh is always positioned so the bottom right corner is (0,0,0)

In [16]:
o3d.visualization.draw_geometries([mesh, mesh_coord_frame])
mesh_r_old = copy.deepcopy(mesh)

In [17]:
#Rotation check!!!
# Not working
mesh_r = copy.deepcopy(mesh)
R = mesh.get_rotation_matrix_from_xyz((0, 2*np.pi/3 , 0))
mesh_r.rotate(R, center=(0,0,0))
mesh_r.paint_uniform_color([1, 0.706, 0])
box_mesh_coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100, origin=[0, 0, 0])
o3d.visualization.draw_geometries([mesh_r, box_mesh_coord_frame, mesh, rect_mesh])



new approach: 

find the center of mass of the vertices and then translate the whole mesh by the center of mass (edited) 
They might have a function to do that for you but maybe not
once it's translated, apply rotation and then translate it back to where it was if you want it  there

In [18]:
mesh_path = './models/Aric Board 2.stl'
mesh = o3d.io.read_triangle_mesh(mesh_path)
mesh.compute_vertex_normals()
old_center = mesh.get_center()
mesh = mesh.translate(old_center*(-1))


old_center = rect_mesh.get_center()
rect_mesh = rect_mesh.translate(old_center*(-1))
coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100, origin=[0, 0, 0])

o3d.visualization.draw_geometries([coord_frame, mesh, rect_mesh])

In [19]:
mesh_copy = copy.deepcopy(mesh)
mesh_copy.rotate(mesh_copy.get_rotation_matrix_from_xyz((np.pi / 2, 0, np.pi / 4)), center=(0, 0, 0))
mesh_copy.paint_uniform_color([1, 0.706, 0])

o3d.visualization.draw_geometries([coord_frame, mesh, rect_mesh, mesh_copy])

In [20]:
# source: https://stackoverflow.com/questions/70160183/how-can-i-align-register-two-meshes-in-open3d-python
#Does not WOrK!!!

#Since it is alot easier to adjust via blender, will save the each centered object, rotate manually, and reimport back to this notebook

o3d.io.write_triangle_mesh("defective_mesh.stl", mesh)
rect_mesh.compute_vertex_normals()

o3d.io.write_triangle_mesh("rect_mesh.stl", rect_mesh)


True

Adjustments made:

Location X: -11.46 m
Y: 2.85 m
Z: 1.43m

Rotation X: 60.4 deg
Y: 5.1 deg
Z: 84.6 deg

Scale X: 1
Y: 1
Z: 1

In [21]:
rect_mesh = o3d.io.read_triangle_mesh("rect_mesh_aligned.stl")
rect_mesh.compute_vertex_normals()
coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100, origin=[0, 0, 0])

o3d.visualization.draw_geometries([rect_mesh, coord_frame])

def_mesh = o3d.io.read_triangle_mesh("def_mesh_aligned.stl")
def_mesh.compute_vertex_normals()
coord_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100, origin=[0, 0, 0])

o3d.visualization.draw_geometries([def_mesh, coord_frame])

In [22]:
rect_cloud = rect_mesh.sample_points_uniformly(500)
def_cloud = def_mesh.sample_points_uniformly(500)

downs_def = def_cloud.voxel_down_sample(voxel_size=5)
o3d.visualization.draw_geometries([def_cloud])
print(downs_def)
print(rect_cloud)
print(def_cloud)

PointCloud with 484 points.
PointCloud with 500 points.
PointCloud with 500 points.


In [23]:
#https://github.com/isl-org/Open3D/pull/1884/commits/d739cc20e4f54798aacca5f32b36f5a3066531a6
dists = rect_cloud.compute_point_cloud_distance(def_cloud)
dists = np.asarray(dists)
ind = np.where(dists > 0.01)[0]
res = rect_cloud.select_by_index(ind)
o3d.visualization.draw_geometries([res])

Not just the wane - try scaling??

In [24]:
rect_mesh_c = copy.deepcopy(rect_mesh)
rect_mesh_c.scale(0.95, center=rect_mesh_c.get_center())

o3d.visualization.draw_geometries([rect_mesh_c, def_mesh])

In [25]:
rect_cloud = rect_mesh.sample_points_uniformly(1000)
def_cloud = def_mesh.sample_points_uniformly(1000)

dists = rect_cloud.compute_point_cloud_distance(def_cloud)
dists = np.asarray(dists)
ind = np.where(dists <  10)[0]
res = rect_cloud.select_by_index(ind)
o3d.visualization.draw_geometries([res, def_mesh])

In [26]:

with o3d.utility.VerbosityContextManager(
        o3d.utility.VerbosityLevel.Debug) as cm:
    labels = np.array(
        res.cluster_dbscan(eps=10, min_points=5, print_progress=True))

max_label = labels.max()
print(f"point cloud has {max_label + 1} clusters")
colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0
res.colors = o3d.utility.Vector3dVector(colors[:, :3])
o3d.visualization.draw_geometries([res])

[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 40
point cloud has 40 clusters
Precompute neighbors.[========================================] 100%


In [27]:
rect_mesh = o3d.io.read_triangle_mesh("rect_mesh_aligned.stl")
rect_mesh = o3d.t.geometry.TriangleMesh.from_legacy(rect_mesh)

def_mesh = o3d.io.read_triangle_mesh("def_mesh_aligned.stl")
def_mesh = o3d.t.geometry.TriangleMesh.from_legacy(def_mesh)

res = rect_mesh.boolean_difference(def_mesh)
res.compute_vertex_normals()
o3d.visualization.draw([res])

Don't understand hwo this is not a function, there is literally a test for it in the github repo. can do this in blender!!!! http://www.open3d.org/docs/release/python_api/open3d.t.geometry.TriangleMesh.html#open3d.t.geometry.TriangleMesh.boolean_difference

To do this in blender, click the defective board, then hold shift and click the perfect board. go to modifier properties (wrench icon), then click add modifier. click boolean, then choose difference. Choose the object that you will be subtracting with, and voila!

In [ ]:
bool_diff = o3d.io.read_triangle_mesh("boolean_diff.stl")
bool_diff.compute_vertex_normals()
o3d.visualization.draw_geometries([bool_diff])
def_cloud = def_mesh.sample_points_uniformly(500)



In [ ]:
mesh_in = o3d.io.read_triangle_mesh("boolean_diff.stl")
mesh_in.compute_vertex_normals()

print(
    f'Input mesh has {len(mesh_in.vertices)} vertices and {len(mesh_in.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh_in])

voxel_size = max(mesh_in.get_max_bound() - mesh_in.get_min_bound()) / 32
print(f'voxel_size = {voxel_size:e}')
mesh_smp = mesh_in.simplify_vertex_clustering(
    voxel_size=voxel_size,
    contraction=o3d.geometry.SimplificationContraction.Average)
print(
    f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh_smp])

voxel_size = max(mesh_in.get_max_bound() - mesh_in.get_min_bound()) / 16
print(f'voxel_size = {voxel_size:e}')
mesh_smp = mesh_in.simplify_vertex_clustering(
    voxel_size=voxel_size,
    contraction=o3d.geometry.SimplificationContraction.Average)
print(
    f'Simplified mesh has {len(mesh_smp.vertices)} vertices and {len(mesh_smp.triangles)} triangles'
)
o3d.visualization.draw_geometries([mesh_smp])

Input mesh has 3571409 vertices and 1197190 triangles
voxel_size = 1.524850e+01
Simplified mesh has 612 vertices and 2285 triangles
voxel_size = 3.049700e+01
Simplified mesh has 136 vertices and 567 triangles
